development:
  adapter: postgresql
  database: spree_puntopagos_development
  pool: 5
  username: mespina
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: spree_puntopagos_test
  pool: 5
  username: mespina
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: spree_puntopagos_production
  pool: 5
  username: mespina
  password:
  host: localhost
  port: 5432

